-- =====================================================
-- Migration 019: Rescue Kit Interactive Portal Version
-- =====================================================
-- Adds 3 new tables for persistent user data:
--   - assessment_results (append-only history)
--   - form_responses (upsert per user/lesson/form)
--   - practice_plan_progress (upsert per user/lesson/plan)
--
-- Adds the 'multi' access_grants type (semantic only — jsonb schema unchanged).
-- Creates the Rescue Kit course with 3 modules and 14 lessons (empty content_json).
-- Updates the existing rescue-kit product to use multi access_grants.
-- Extends link_purchases_on_signup() to handle the multi type.
--
-- IMPORTANT: Content for the 14 lessons is seeded separately via UPDATE
-- statements generated by `course-lab/tools/md_to_blocks.py`. This migration
-- creates the lesson ROWS but leaves content_json as empty arrays.
-- =====================================================

-- =====================================================
-- NEW TABLES
-- =====================================================

CREATE TABLE assessment_results (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id uuid NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  assessment_id text NOT NULL,
  responses jsonb NOT NULL,
  total_score integer NOT NULL,
  result_zone text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_assessment_results_user_lesson_created
  ON assessment_results(user_id, lesson_id, created_at DESC);

CREATE TABLE form_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id uuid NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  form_id text NOT NULL,
  fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT form_responses_user_lesson_form_unique UNIQUE (user_id, lesson_id, form_id)
);

CREATE TABLE practice_plan_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_id uuid NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
  plan_id text NOT NULL,
  days_completed jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes_per_day jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT practice_plan_progress_user_lesson_plan_unique UNIQUE (user_id, lesson_id, plan_id)
);

-- =====================================================
-- RLS POLICIES
-- =====================================================

ALTER TABLE assessment_results ENABLE ROW LEVEL SECURITY;

CREATE POLICY "assessment_results_user_select" ON assessment_results
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "assessment_results_user_insert" ON assessment_results
  FOR INSERT WITH CHECK (auth.uid() = user_id);
-- No UPDATE or DELETE — results are append-only history

ALTER TABLE form_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "form_responses_user_select" ON form_responses
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "form_responses_user_insert" ON form_responses
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "form_responses_user_update" ON form_responses
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "form_responses_user_delete" ON form_responses
  FOR DELETE USING (auth.uid() = user_id);

ALTER TABLE practice_plan_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "practice_plan_progress_user_select" ON practice_plan_progress
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "practice_plan_progress_user_insert" ON practice_plan_progress
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "practice_plan_progress_user_update" ON practice_plan_progress
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "practice_plan_progress_user_delete" ON practice_plan_progress
  FOR DELETE USING (auth.uid() = user_id);

-- =====================================================
-- RESCUE KIT COURSE SEED
-- =====================================================
-- Schema verified against migration 001 on 2026-04-11:
--   courses(slug, title, description, price_cents NOT NULL, stripe_price_id, stripe_sub_price_id,
--           course_type CHECK IN ('flagship','bundle','subscription_content'), is_active)
--   modules(course_id, module_number, title, description, sort_order, is_preview)
--   lessons(module_id, title, sort_order, content_json, mux_asset_id, mux_playback_id,
--           duration_seconds, has_workbook, workbook_storage_path, is_preview)
-- Neither modules nor lessons have a 'slug' column. URL routing is presumed to use
-- module_number + lesson title/sort_order — verify in CoursePortal.jsx on Monday.
-- Migration 004 added parent_lesson_id to lessons (not used for Rescue Kit v1 — keeping it flat).
-- =====================================================

DO $$
DECLARE
  rescue_kit_course_id uuid;
  module_part_i_id uuid;
  module_part_ii_id uuid;
  module_afterword_id uuid;
BEGIN
  -- Create the Rescue Kit course
  -- course_type='bundle' keeps it off the Programs page (which filters to 'flagship')
  -- price_cents=3900 matches the rescue-kit product in the products table
  INSERT INTO courses (slug, title, description, price_cents, course_type, is_active)
  VALUES (
    'rescue-kit',
    'The Conflict Rescue Kit',
    'A standalone toolkit for couples who want to fight better. First aid for when conflict is the primary pain point. Includes the SPARK Method, Zones of Resilience self-assessment, Conflict Recovery Plan, and a 7-day practice plan.',
    3900,
    'bundle',
    true
  )
  RETURNING id INTO rescue_kit_course_id;

  -- Module 1: Part I -- The Emergency Mini-Kit
  -- Note: modules table uses 'module_number' (text) and 'sort_order' (integer)
  INSERT INTO modules (course_id, module_number, title, description, sort_order, is_preview)
  VALUES (
    rescue_kit_course_id,
    '1',
    'Part I -- The Emergency Mini-Kit',
    'For when you need this right now. Every tool in Part I is designed to be used in under five minutes.',
    1,
    false
  )
  RETURNING id INTO module_part_i_id;

  -- Module 2: Part II -- The Book
  INSERT INTO modules (course_id, module_number, title, description, sort_order, is_preview)
  VALUES (
    rescue_kit_course_id,
    '2',
    'Part II -- The Book',
    'The deeper work, for a day when you have time to read.',
    2,
    false
  )
  RETURNING id INTO module_part_ii_id;

  -- Module 3: Afterword & More
  INSERT INTO modules (course_id, module_number, title, description, sort_order, is_preview)
  VALUES (
    rescue_kit_course_id,
    '3',
    'Afterword and More',
    'Closing thoughts, about Trisha and Jeff, and what comes next.',
    3,
    false
  )
  RETURNING id INTO module_afterword_id;

  -- Module 1 Lessons (5 tools in the Emergency Mini-Kit)
  -- Note: lessons table has no slug column. Navigation uses title + sort_order.
  -- content_json starts empty; Sunday's converter run populates it via UPDATE statements in a
  -- separate migration file (020_rescue_kit_content_seed.sql).
  INSERT INTO lessons (module_id, title, content_json, sort_order, is_preview)
  VALUES
    (module_part_i_id, 'Start Here', '[]'::jsonb, 1, false),
    (module_part_i_id, 'The 30-Second Reset', '[]'::jsonb, 2, false),
    (module_part_i_id, 'The SPARK Method (Quick Reference)', '[]'::jsonb, 3, false),
    (module_part_i_id, 'Where Do You Live Right Now?', '[]'::jsonb, 4, false),
    (module_part_i_id, 'The Conflict Recovery Plan', '[]'::jsonb, 5, false);

  -- Module 2 Lessons (6 chapters)
  INSERT INTO lessons (module_id, title, content_json, sort_order, is_preview)
  VALUES
    (module_part_ii_id, 'Chapter 1 -- The Moment It Shifts', '[]'::jsonb, 1, false),
    (module_part_ii_id, 'Chapter 2 -- Your Critter Brain and Your CEO Brain', '[]'::jsonb, 2, false),
    (module_part_ii_id, 'Chapter 3 -- Riding the 90-Second Wave', '[]'::jsonb, 3, false),
    (module_part_ii_id, 'Chapter 4 -- The Zones You Live In', '[]'::jsonb, 4, false),
    (module_part_ii_id, 'Chapter 5 -- The SPARK Method', '[]'::jsonb, 5, false),
    (module_part_ii_id, 'Chapter 6 -- After the Storm: Your Practice Plan', '[]'::jsonb, 6, false);

  -- Module 3 Lessons (3 back-matter sections)
  INSERT INTO lessons (module_id, title, content_json, sort_order, is_preview)
  VALUES
    (module_afterword_id, 'Afterword', '[]'::jsonb, 1, false),
    (module_afterword_id, 'About Trisha and Jeff', '[]'::jsonb, 2, false),
    (module_afterword_id, 'What Comes Next', '[]'::jsonb, 3, false);

  -- =====================================================
  -- UPDATE EXISTING RESCUE-KIT PRODUCT TO MULTI ACCESS
  -- =====================================================
  -- The rescue-kit product already exists with download-only access.
  -- We update it to multi so one purchase grants BOTH the PDF download
  -- AND enrollment in the interactive course.
  -- =====================================================

  UPDATE products
  SET access_grants = jsonb_build_object(
    'type', 'multi',
    'grants', jsonb_build_array(
      jsonb_build_object(
        'type', 'download',
        'download_slug', 'rescue-kit'
      ),
      jsonb_build_object(
        'type', 'enrollment',
        'course_id', rescue_kit_course_id::text
      )
    )
  ),
  updated_at = now()
  WHERE slug = 'rescue-kit';

  RAISE NOTICE 'Rescue Kit Interactive migration complete. Course ID: %', rescue_kit_course_id;
END $$;

-- =====================================================
-- EXTEND link_purchases_on_signup FOR MULTI TYPE
-- =====================================================
-- The existing function handles enrollment and download types.
-- We extend it to iterate through multi-type grants.
-- =====================================================

CREATE OR REPLACE FUNCTION link_purchases_on_signup()
RETURNS TRIGGER AS $$
DECLARE
  contact_record RECORD;
  order_record RECORD;
  grant_record jsonb;
  err_msg text;
  linked_count integer := 0;
BEGIN
  SELECT * INTO contact_record
  FROM crm_contacts
  WHERE email = NEW.email;

  IF NOT FOUND THEN
    RAISE LOG 'link_purchases_on_signup: no CRM contact for %', NEW.email;
    RETURN NEW;
  END IF;

  UPDATE crm_contacts
  SET auth_user_id = NEW.id
  WHERE id = contact_record.id;

  FOR order_record IN
    SELECT o.id as order_id, o.stripe_payment_intent, p.access_grants
    FROM orders o
    JOIN products p ON p.slug = o.product_slug
    WHERE o.contact_id = contact_record.id
      AND o.status = 'completed'
  LOOP
    UPDATE orders SET auth_user_id = NEW.id WHERE id = order_record.order_id;
    linked_count := linked_count + 1;

    IF (order_record.access_grants->>'type') = 'enrollment' THEN
      INSERT INTO enrollments (user_id, course_id, status, stripe_payment_id)
      VALUES (
        NEW.id,
        (order_record.access_grants->>'course_id')::uuid,
        'active',
        order_record.stripe_payment_intent
      )
      ON CONFLICT (user_id, course_id) DO NOTHING;
    ELSIF (order_record.access_grants->>'type') = 'multi' THEN
      FOR grant_record IN SELECT * FROM jsonb_array_elements(order_record.access_grants->'grants')
      LOOP
        IF (grant_record->>'type') = 'enrollment' THEN
          INSERT INTO enrollments (user_id, course_id, status, stripe_payment_id)
          VALUES (
            NEW.id,
            (grant_record->>'course_id')::uuid,
            'active',
            order_record.stripe_payment_intent
          )
          ON CONFLICT (user_id, course_id) DO NOTHING;
        END IF;
        -- download type: no enrollment row needed
      END LOOP;
    END IF;
    -- Single 'download' type: no enrollment row needed
  END LOOP;

  RAISE LOG 'link_purchases_on_signup: linked % orders for user % (email %)',
    linked_count, NEW.id, NEW.email;

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  GET STACKED DIAGNOSTICS err_msg = MESSAGE_TEXT;
  RAISE WARNING 'link_purchases_on_signup FAILED for user % (email %): %',
    NEW.id, NEW.email, err_msg;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger already exists from migration 016, no need to recreate.
