-- 032_webinar_may21.sql
-- Reschedule "The Patterns Running Your Marriage" workshop from
-- April 30, 2026 to May 21, 2026 at 7:00 PM MDT (UTC-6 during DST).
--
-- Apr 30 row id: 93a564a5-4c73-4d8a-91ad-8a017ea1442e (4 existing registrants).
-- Cleanest reschedule path is to UPDATE the existing row in place: registrant
-- FKs stay intact and the day-before/day-of reminder cron auto-rebases off the
-- new starts_at. No new row needed; the page code is fully data-driven from
-- this row, so updating starts_at / meeting_url updates the surface.
--
-- Status: NOT YET APPLIED. Generated by Team B 2026-04-29. Apply via
-- Supabase Dashboard SQL editor or `supabase migration up` after Chase
-- confirms the Meet URL choice (see comment below).

-- ----------------------------------------------------------------------------
-- Update the workshop row.
--
-- meeting_url: defaults to the April 23 Meet link reused for May 21. CHANGE
-- this before applying if Trisha generates a new Meet event for May 21.
-- ----------------------------------------------------------------------------

UPDATE public.webinars
SET
  starts_at = '2026-05-22 01:00:00+00',  -- May 21 7:00 PM MDT
  duration_minutes = 90,
  status = 'scheduled',
  meeting_url = 'https://meet.google.com/cam-fqwt-jdn',
  -- Clear the placeholder Riverside URL so the WebinarLive.jsx fallback chain
  -- correctly picks up meeting_url first (avoids the iframe-on-Meet-link bug).
  riverside_audience_url = NULL
WHERE id = '93a564a5-4c73-4d8a-91ad-8a017ea1442e';

-- ----------------------------------------------------------------------------
-- DATA HYGIENE: flip stale Apr 23 webinar rows to 'completed'.
--
-- Both Apr 23 rows (cf709b00, c7724cc2) still have status='scheduled' as of
-- 2026-04-29, six days after the event. Because the /webinar page queries
-- "earliest scheduled webinar", these stale rows currently RANK ABOVE the
-- May 21 row in the upcoming-webinar query — so even after this migration's
-- UPDATE lands, the page would still display the stale Apr 23 event until the
-- statuses are fixed.
--
-- Marking 'completed' (not 'evergreen' — neither has a replay_url) hides them
-- from /webinar's upcoming query. Replay page still won't surface them
-- because replay_url IS NULL.
-- ----------------------------------------------------------------------------

UPDATE public.webinars
SET status = 'completed'
WHERE id IN (
  'cf709b00-a5c8-4313-a668-0211a5775a29',  -- Spark Challenge Webinar — Live Q&A
  'c7724cc2-502f-48e1-b828-58c239061a45'   -- When a Spark Starts a Fire
)
AND status = 'scheduled';

-- ----------------------------------------------------------------------------
-- Sanity check: verify the update landed on exactly one row with the right
-- shape. Run after applying.
-- ----------------------------------------------------------------------------
--
--   SELECT id, title, starts_at, duration_minutes, status,
--          meeting_url, riverside_audience_url, registrant_count
--   FROM public.webinars
--   WHERE id = '93a564a5-4c73-4d8a-91ad-8a017ea1442e';
--
-- Expected:
--   starts_at = 2026-05-22 01:00:00+00
--   meeting_url = https://meet.google.com/cam-fqwt-jdn (or whatever Chase chose)
--   riverside_audience_url = NULL
--   status = scheduled
--   registrant_count = 4 (preserved)

-- ----------------------------------------------------------------------------
-- ALTERNATIVE (commented out): if Chase prefers to leave the old row alone and
-- insert a NEW row for May 21 (e.g., to keep an audit trail of the original
-- April 30 event), use this block instead. Note: existing 4 registrants on the
-- old row will NOT auto-roll forward; they need a manual cross-insert into
-- webinar_registrations against the new id, OR a "we rescheduled, please
-- re-register" email.
-- ----------------------------------------------------------------------------
--
-- -- Step 1: soft-cancel the original April 30 row.
-- UPDATE public.webinars
-- SET status = 'completed'  -- soft-cancel; 'completed' hides from upcoming queries
-- WHERE id = '93a564a5-4c73-4d8a-91ad-8a017ea1442e';
--
-- -- Step 2: insert the May 21 row.
-- INSERT INTO public.webinars (
--   title,
--   description,
--   starts_at,
--   duration_minutes,
--   meeting_url,
--   status
-- ) VALUES (
--   'The Patterns Running Your Marriage',
--   'A 90-minute live workshop with Jeff & Trisha on the nervous-system patterns that hijack your conversations.',
--   '2026-05-22 01:00:00+00',
--   90,
--   'https://meet.google.com/cam-fqwt-jdn',
--   'scheduled'
-- );
